export const metadata = {
  title: 'Data Fetching Techniques Next Level Next JS',
  description: 'Generated by Next.js',
}
import "../styles/globals.css"
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
